# --- Player Roles ---
ROLE_NONE = None # Default before selection
ROLE_WHITE_HAT = "WHITE_HAT"
ROLE_GREY_HAT = "GREY_HAT"
ROLE_BLACK_HAT = "BLACK_HAT"

# --- Role-Based Command Access ---
COMMAND_ACCESS = {
    ROLE_WHITE_HAT: {
        "allowed_main": ["help", "clear", "theme", "type", "burst", "sequence", "corrupt", "flicker", "colorchange", "overlay", "jiggle", "screenres", "fullscreen", "windowed", "pwd", "ls", "cd", "cat", "grep", "scan", "parse", "restore", "mkdir", "touch", "echo", "whoami", "hostname", "uname", "head", "tail", "status", "processes", "kill", "msfconsole", "quit", "exit", "integrity_check", "start_puzzle"],
        "allowed_msf": ["help", "clear", "search", "use", "info", "show options", "set", "back", "exit", "sessions"], # No run/exploit
        "allowed_puzzle": ["help", "solve", "hint", "exit_puzzle", "theme", "quit", "exit"], # Commands available when a puzzle is active
        "help_text_main": {
            "grep": "  grep <pattern> <file> - Search for PATTERN in FILE",
            "scan": "  scan <file>       - Analyze a file for corruption",
            "parse": "  parse <file>      - Attempt to extract readable data from a file",
            "restore": "  restore <file>    - Attempt to repair a corrupted file",
            "integrity_check": "  integrity_check   - Performs a basic system integrity scan",
            "start_puzzle": "  start_puzzle <id> - Activate a puzzle challenge",
            "help": "  help              - Show this help message",
            "clear": "  clear             - Clear the terminal screen",
            "theme": "  theme <name>      - Change terminal theme (e.g., default, kali, nightmare, dos)",
            "type": "  type <text>       - Simulate typing the given text",
            "burst": "  burst <text>      - Instantly display the given text",
            "sequence": "  sequence          - Demonstrate a sequence of typing and delays",
            "corrupt": "  corrupt <off> [dur] [int] [rate] - Corrupt line (e.g., corrupt -1 2000 50 50)",
            "flicker": "  flicker <off> [dur] [rate] [key] - Flicker line (e.g., flicker -1 1500 80 error)",
            "colorchange": "  colorchange <off> <dur> [fg] [bg] - Temp change line color (e.g., colorchange -1 1000 err hi)",
            "overlay": "  overlay [dur] [num] [key] [rate] - Show text overlay (e.g., overlay 1500 50 err 80)",
            "jiggle": "  jiggle <off> [dur] [int] [rate] - Jiggle line (e.g., jiggle -1 1000 2 50)",
            "screenres": "  screenres <W>x<H> - Change screen resolution (e.g., screenres 800x600)",
            "fullscreen": "  fullscreen        - Switch to fullscreen mode",
            "windowed": "  windowed          - Switch to windowed mode",
            "pwd": "  pwd               - Print working directory",
            "ls": "  ls                - List directory contents",
            "cd": "  cd <dir>          - Change directory",
            "cat": "  cat <file>        - Display file content",
            "mkdir": "  mkdir <dirname>   - Create a new directory",
            "touch": "  touch <filename>  - Create/update file",
            "echo": "  echo [text]       - Print text",
            "whoami": "  whoami            - Print current username",
            "hostname": "  hostname          - Print hostname",
            "uname": "  uname [-a]        - Print system information",
            "head": "  head [-n N] <file>- Show first N lines",
            "tail": "  tail [-n N] <file>- Show last N lines",
            "status": "  status            - Display system status overview",
            "processes": "  processes         - List running simulated processes",
            "kill": "  kill <pid>        - Terminate a simulated process",
            "msfconsole": "  msfconsole        - Start the Metasploit console",
            "quit": "  quit              - Exit the game",
            "exit": "  exit              - Exit the game (alias for quit)"
        },
        "help_text_puzzle": {
            "solve": "  solve <answer>    - Attempt to solve the active puzzle",
            "hint": "  hint              - Get a hint for the active puzzle",
            "exit_puzzle": "  exit_puzzle       - Leave the current puzzle",
            "help": "  help              - Show puzzle mode help",
            "theme": "  theme <name>      - Change terminal theme",
            "quit": "  quit              - Exit the game",
            "exit": "  exit              - Exit the game (alias for quit)"
        },
        "help_text_msf": {
            "clear": "  clear            - Clear the msfconsole screen",
            "help": "  help             - Show this help",
            "search": "  search <keyword> - Search for modules",
            "use": "  use <module>     - Select a module",
            "info": "  info [module]    - Display information about a module",
            "show options": "  show options     - Show options for the current module",
            "set": "  set <opt> <val>  - Set an option",
            "sessions": "  sessions [-l]    - List active sessions",
            "back": "  back             - Return to the main terminal",
            "exit": "  exit             - Exit msfconsole"
        }
    },
    ROLE_GREY_HAT: {
        "allowed_main": ["help", "clear", "theme", "type", "burst", "sequence", "corrupt", "flicker", "colorchange", "overlay", "jiggle", "screenres", "fullscreen", "windowed", "pwd", "ls", "cd", "cat", "grep", "scan", "parse", "restore", "mkdir", "touch", "echo", "whoami", "hostname", "uname", "head", "tail", "rm", "mv", "status", "processes", "kill", "msfconsole", "quit", "exit", "observe_traffic", "start_puzzle"],
        "allowed_msf": ["help", "clear", "search", "use", "info", "show options", "set", "run", "exploit", "back", "exit", "sessions"],
        "allowed_puzzle": ["help", "solve", "hint", "exit_puzzle", "theme", "quit", "exit"],
        "help_text_main": { # Grey Hat sees all standard commands
            "grep": "  grep <pattern> <file> - Search for PATTERN in FILE",
            "scan": "  scan <file>       - Analyze a file for corruption",
            "parse": "  parse <file>      - Attempt to extract readable data from a file",
            "restore": "  restore <file>    - Attempt to repair a corrupted file",
            "observe_traffic": "  observe_traffic   - Monitors network traffic for anomalies",
            "start_puzzle": "  start_puzzle <id> - Activate a puzzle challenge",
            "help": "  help              - Show this help message",
            "clear": "  clear             - Clear the terminal screen",
            "theme": "  theme <name>      - Change terminal theme",
            "type": "  type <text>       - Simulate typing the given text",
            "burst": "  burst <text>      - Instantly display the given text",
            "sequence": "  sequence          - Demonstrate a sequence of typing and delays",
            "corrupt": "  corrupt <off> [dur] [int] [rate] - Corrupt line",
            "flicker": "  flicker <off> [dur] [rate] [key] - Flicker line",
            "colorchange": "  colorchange <off> <dur> [fg] [bg] - Temp change line color",
            "overlay": "  overlay [dur] [num] [key] [rate] - Show text overlay",
            "jiggle": "  jiggle <off> [dur] [int] [rate] - Jiggle line",
            "screenres": "  screenres <W>x<H> - Change screen resolution",
            "fullscreen": "  fullscreen        - Switch to fullscreen mode",
            "windowed": "  windowed          - Switch to windowed mode",
            "pwd": "  pwd               - Print working directory",
            "ls": "  ls                - List directory contents",
            "cd": "  cd <dir>          - Change directory",
            "cat": "  cat <file>        - Display file content",
            "mkdir": "  mkdir <dirname>   - Create a new directory",
            "touch": "  touch <filename>  - Create/update file",
            "echo": "  echo [text]       - Print text",
            "whoami": "  whoami            - Print current username",
            "hostname": "  hostname          - Print hostname",
            "uname": "  uname [-a]        - Print system information",
            "head": "  head [-n N] <file>- Show first N lines",
            "tail": "  tail [-n N] <file>- Show last N lines",
            "rm": "  rm <file/dir>     - Remove a file or directory",
            "mv": "  mv <src> <dest>   - Move/rename a file or directory",
            "status": "  status            - Display system status overview",
            "processes": "  processes         - List running simulated processes",
            "kill": "  kill <pid>        - Terminate a simulated process",
            "msfconsole": "  msfconsole        - Start the Metasploit console",
            "quit": "  quit              - Exit the game",
            "exit": "  exit              - Exit the game (alias for quit)"
        },
        "help_text_puzzle": {
            "solve": "  solve <answer>    - Attempt to solve the active puzzle",
            "hint": "  hint              - Get a hint for the active puzzle",
            "exit_puzzle": "  exit_puzzle       - Leave the current puzzle",
            "help": "  help              - Show puzzle mode help",
            "theme": "  theme <name>      - Change terminal theme",
            "quit": "  quit              - Exit the game",
            "exit": "  exit              - Exit the game (alias for quit)"
        },
        "help_text_msf": { # Grey Hat sees all msf commands
            "clear": "  clear            - Clear the msfconsole screen",
            "help": "  help             - Show this help",
            "search": "  search <keyword> - Search for modules",
            "use": "  use <module>     - Select a module",
            "info": "  info [module]    - Display information about a module",
            "show options": "  show options     - Show options for the current module",
            "set": "  set <opt> <val>  - Set an option",
            "run": "  run / exploit    - Execute the current module",
            "exploit": "  run / exploit    - Execute the current module (alias for run)",
            "sessions": "  sessions [-l]    - List active sessions",
            "back": "  back             - Return to the main terminal",
            "exit": "  exit             - Exit msfconsole"
        }
    },
    ROLE_BLACK_HAT: { # Same as Grey Hat for now, can diverge later
        "allowed_main": ["help", "clear", "theme", "type", "burst", "sequence", "corrupt", "flicker", "colorchange", "overlay", "jiggle", "screenres", "fullscreen", "windowed", "pwd", "ls", "cd", "cat", "grep", "scan", "parse", "restore", "mkdir", "touch", "echo", "whoami", "hostname", "uname", "head", "tail", "rm", "mv", "status", "processes", "kill", "msfconsole", "quit", "exit", "find_exploit", "start_puzzle"],
        "allowed_msf": ["help", "clear", "search", "use", "info", "show options", "set", "run", "exploit", "back", "exit", "sessions"],
        "allowed_puzzle": ["help", "solve", "hint", "exit_puzzle", "theme", "quit", "exit"],
        "help_text_main": { # Black Hat sees all standard commands
            "grep": "  grep <pattern> <file> - Search for PATTERN in FILE",
            "scan": "  scan <file>       - Analyze a file for corruption",
            "parse": "  parse <file>      - Attempt to extract readable data from a file",
            "restore": "  restore <file>    - Attempt to repair a corrupted file",
            "find_exploit": "  find_exploit      - Searches for known vulnerabilities in the current system",
            "start_puzzle": "  start_puzzle <id> - Activate a puzzle challenge",
            "help": "  help              - Show this help message",
            "clear": "  clear             - Clear the terminal screen",
            "theme": "  theme <name>      - Change terminal theme",
            "type": "  type <text>       - Simulate typing the given text",
            "burst": "  burst <text>      - Instantly display the given text",
            "sequence": "  sequence          - Demonstrate a sequence of typing and delays",
            "corrupt": "  corrupt <off> [dur] [int] [rate] - Corrupt line",
            "flicker": "  flicker <off> [dur] [rate] [key] - Flicker line",
            "colorchange": "  colorchange <off> <dur> [fg] [bg] - Temp change line color",
            "overlay": "  overlay [dur] [num] [key] [rate] - Show text overlay",
            "jiggle": "  jiggle <off> [dur] [int] [rate] - Jiggle line",
            "screenres": "  screenres <W>x<H> - Change screen resolution",
            "fullscreen": "  fullscreen        - Switch to fullscreen mode",
            "windowed": "  windowed          - Switch to windowed mode",
            "pwd": "  pwd               - Print working directory",
            "ls": "  ls                - List directory contents",
            "cd": "  cd <dir>          - Change directory",
            "cat": "  cat <file>        - Display file content",
            "mkdir": "  mkdir <dirname>   - Create a new directory",
            "touch": "  touch <filename>  - Create/update file",
            "echo": "  echo [text]       - Print text",
            "whoami": "  whoami            - Print current username",
            "hostname": "  hostname          - Print hostname",
            "uname": "  uname [-a]        - Print system information",
            "head": "  head [-n N] <file>- Show first N lines",
            "tail": "  tail [-n N] <file>- Show last N lines",
            "rm": "  rm <file/dir>     - Remove a file or directory",
            "mv": "  mv <src> <dest>   - Move/rename a file or directory",
            "status": "  status            - Display system status overview",
            "processes": "  processes         - List running simulated processes",
            "kill": "  kill <pid>        - Terminate a simulated process",
            "msfconsole": "  msfconsole        - Start the Metasploit console",
            "quit": "  quit              - Exit the game",
            "exit": "  exit              - Exit the game (alias for quit)"
        },
        "help_text_puzzle": {
            "solve": "  solve <answer>    - Attempt to solve the active puzzle",
            "hint": "  hint              - Get a hint for the active puzzle",
            "exit_puzzle": "  exit_puzzle       - Leave the current puzzle",
            "help": "  help              - Show puzzle mode help",
            "theme": "  theme <name>      - Change terminal theme",
            "quit": "  quit              - Exit the game",
            "exit": "  exit              - Exit the game (alias for quit)"
        },
        "help_text_msf": { # Black Hat sees all msf commands
            "clear": "  clear            - Clear the msfconsole screen",
            "help": "  help             - Show this help",
            "search": "  search <keyword> - Search for modules",
            "use": "  use <module>     - Select a module",
            "info": "  info [module]    - Display information about a module",
            "show options": "  show options     - Show options for the current module",
            "set": "  set <opt> <val>  - Set an option",
            "run": "  run / exploit    - Execute the current module",
            "exploit": "  run / exploit    - Execute the current module (alias for run)",
            "sessions": "  sessions [-l]    - List active sessions",
            "back": "  back             - Return to the main terminal",
            "exit": "  exit             - Exit msfconsole"
        }
    }
}